### ISSUE TITLE
Metatranscriptome and metaproteome data seems to mostly be missing

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#243]
Track down the source of this missing daata

**Comment by subdavis** [comment]
Fixed in #249

**Comment by jeffbaumes** [comment]
I'm still seeing at least some empty (no data object) transcriptomes, reopening to track this

**Comment by jbeezley** [comment]
I think there have been changes to the source data since we last ingested.  The ingestion no longer happens on deploy out of necessity.  I'll have the code to manually trigger an ingest ready soon, then we can check if they are still missing.

**Comment by jeffbaumes** [comment]
Ok it appears proteomics is there and transcriptome is there apart from URLs, so this particular issue is resolved now.
